### PR TITLE
Travis config for syncing template

### LINKED ISSUE #83: Use travis cron job to sync templates?
We can have a cron job every week or so in travis in order to sync the templates. A manual inspection will be needed after the code is pushed into a different branch. After that a PR can be created and merged into the master branch. This will reduce the overhead of syncing and the repo will never be out of sync for a long time.

What do you think @chfw ?

### PR DESCRIPTION
**Pull request by ayan-b**
Also fixes test.

A `GITHUB_TOKEN` env var is needed for the push part.
Closes #83

### CODE REVIEW

**Comment by chfw** [comment]
https://travis-ci.org/moremoban/pypi-mobans/jobs/528197573

failed to build

**Comment by ayan-b** [comment]
We need add a GITHUB_TOKEN as an env var https://travis-ci.org/moremoban/pypi-mobans/jobs/528199994#L469.

**Comment by chfw** [comment]
I see. Let me create one

**Comment by chfw** [comment]
Let me get 0.0.5 out first

**Pull request merged**
